# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eksdemo < Formula
  desc "The easy button for learning, testing and demoing Amazon EKS"
  homepage "https://github.com/awslabs/eksdemo"
  version "0.9.3-test"
  license "MIT-0"

  depends_on "weaveworks/tap/eksctl"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aaroniscode/eksdemo/releases/download/v0.9.3-test/eksdemo_Darwin_arm64.tar.gz"
      sha256 "43205799ab473d09a0d088fe89ae804300915dcb8b874e9521f8c187a0bd3243"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aaroniscode/eksdemo/releases/download/v0.9.3-test/eksdemo_Darwin_x86_64.tar.gz"
      sha256 "17f165e6915d8482d6e136f630d26ebcaac7021cd134f6648e27ddd5664c4785"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaroniscode/eksdemo/releases/download/v0.9.3-test/eksdemo_Linux_arm64.tar.gz"
      sha256 "025f06fbc473a7581804a0d91d0242d711e557a22ddf7807b9bd4d75494cff36"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aaroniscode/eksdemo/releases/download/v0.9.3-test/eksdemo_Linux_x86_64.tar.gz"
      sha256 "c4dc716f337a1ed49680fd530120977d1164d4c7a3ef8962a844920c0c2d369a"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
  end
end
